[project]
name = "whats-on-fip"
version = "0.1.0"
description = ""
authors = [
    { name = "Julen Dixneuf", email = "julen@loudnaround.org" }
]
dependencies = [
    "fastapi>=0.103.2",
    "uvicorn>=0.23.2",
    "loguru>=0.7.2",
    "requests>=2.31.0",
    "python-engineio>=4.8.0",
    "pydantic>=2.4.2",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "pytest>=7.4.2",
    "black>=23.9.1",
    "ruff>=0.0.292",
    "isort>=5.12.0",
    "pytest-asyncio>=0.21.1",
    "pytest-cov>=4.1.0",
    "pytest-mock>=3.11.1",
    "pyright>=1.1.331",
    "httpx>=0.25.0",
]

[tool.hatch.metadata]
allow-direct-references = true

# https://www.python.org/dev/peps/pep-0518/
[tool.isort]
profile = "black"

# Fix deprecation warning
# https://github.com/pytest-dev/pytest-asyncio/blob/d8efa640f0aa1ba8856b908ba486150588018209/pytest_asyncio/plugin.py#L61
[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.ruff]
# Never enforce `E501` (line length violations).
ignore = ["E501"]

[tool.pyright]
include = ["whats_on_fip"]
exclude = ["tests/**"]
