[tool.poetry]
name = "whats-on-fip"
version = "0.1.0"
description = ""
authors = ["Julen Dixneuf <julend@padok.fr>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.86.0"
uvicorn = "^0.19.0"
python-dotenv = "^0.21.0"
loguru = "^0.6.0"
requests = "^2.27.1"
python-engineio = "^4.3.2"

[tool.poetry.dev-dependencies]
pytest = "^7.0"
black = "^22.10"
flake8 = "^5.0.0"
isort = "^5.10.1"
pre-commit = "^2.16.0"
pytest-asyncio = "^0.20.0"
pytest-cov = "^4.0.0"
pytest-mock = "^3.6.1"
mypy = "^0.991"
types-requests = "^2.27.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# https://www.python.org/dev/peps/pep-0518/
[tool.isort]
profile = "black"

# Fix deprecation warning
# https://github.com/pytest-dev/pytest-asyncio/blob/d8efa640f0aa1ba8856b908ba486150588018209/pytest_asyncio/plugin.py#L61
[tool.pytest.ini_options]
asyncio_mode = "auto"

# https://mypy.readthedocs.io/en/stable/config_file.html#using-a-pyproject-toml-file
[tool.mypy]
plugins = "pydantic.mypy"

follow_imports = "silent"
strict_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true
disallow_untyped_defs = true
ignore_missing_imports = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true

[[tool.mypy.overrides]]
module = "tests.*"
ignore_errors = true
