name: Test

on: [push]

env:
  PYTHON_VERSION: "3.9"

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Run image
      uses: abatilo/actions-poetry@v2.1.4
    - name: Install dependencies
      run: make install
    - name: Format with black
      run: |
        make check-format
    - name: Test with pytest
      env:
        RADIO_FRANCE_API_HOST: https://openapi.radiofrance.fr/v1/graphql
        RADIO_FRANCE_API_HEALTHCHECK: https://openapi.radiofrance.fr/v1/.well-known/apollo/server-health
        RADIO_FRANCE_API_TOKEN: ${{ secrets.RADIO_FRANCE_API_TOKEN }}
      run: |
        make test
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
